import Head from "next/head";

export default function Home(props: { label: string }) {
  return (
    <div>
      <Head>
        <title>Color Contrast Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        A simple tool for calculating the contrast ratio between two HEX values. Based on WCAG 2.0 Level AA standards.
      </main>
    </div>
  );
}

export const getStaticProps = () => {
  return {
    props: {  }, 
  };
};
