import Head from "next/head";
import { useState } from "react";

import { Main, Heading, Subtitle, ColorInput, Input, Button, Center } from '../stories/components/components'
import { ContrastChecker } from '../stories/ContrastChecker'

export default function Home() {
  let [colors, setColors] = useState(['#000000']);
  let [result, setResult] = useState(false);

  const onAddColor = () => {
    let items = Object.assign([], colors);
    items.push('#000000');
    setColors(items);
  }

  const onRemoveColor = (index: number) => {
    let items = Object.assign([], colors);
    items.splice(index, 1);
    setColors(items);
  }

  const onChangeEvent = (event: any, index: number) => {
    const color = event.target.value;
    let items: string[] = Object.assign([], colors);
    items[index] = color;
    setColors(items);
  }

  const onTestColors = () => {
    let checker = colors.every(color => /^#([0-9A-F]{3}){1,2}$/i.test(color));

    if (checker) {
      setResult(true);
    }
    else {
      alert('Oops, one of the color not correct!');
    }
  }

  const onTestNewColors = () => {
    setColors(['#000000']);
    setResult(false);  
  }
  return (
    <div>
      <Head>
        <title>Color Contrast Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Main>
          <Heading>
            Color Contrast Checker
          </Heading>
          <Subtitle>
            A simple tool for calculating the contrast ratio between two HEX values. Based on WCAG 2.0 Level AA standards.
          </Subtitle>
        </Main>
        {
          !result ? 
          <div>
            {
              colors.map((color, index) => 
              <ColorInput key={index}>
                <Input type="text" value={color} onChange={(event) => onChangeEvent(event, index)} />
                <Button color="danger" onClick={() => onRemoveColor(index)} disabled={colors.length <= 1}>R</Button>
              </ColorInput>)
            }
            <Center>
              <Button color="success" onClick={() => onAddColor()}>Add</Button>
              <Button color="primary" onClick={() => onTestColors()}>Test</Button>
            </Center>
          </div>: 
          <div>
            <div className="row">
              {
              colors.map((color, index) => <ContrastChecker key={index} color={color} name={null}></ContrastChecker>
              )
              }
            </div>
            <br />
            <Center>
              <Button color="secondary" onClick={() => onTestNewColors()}>Back</Button>
            </Center>
          </div>
        }
      </main>
    </div>
  );
}